
  CREATE TABLE "INTEGRATIONS"."LTF_PAYMODEX_RECON_FILE_DETAILS" 
   (	"ID" NUMBER, 
	"SUPPLIER_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENT_METHOD" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"OIC_FLOW_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

