
  CREATE TABLE "INTEGRATIONS"."LTF_PRICING_INBOUND" 
   (	"PROMOID" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PROMONAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENTCOMPANYCODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"COMPANYCODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SKUCODE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"SHIPSTARTDATE" DATE, 
	"SHIPENDDATE" DATE, 
	"CURRENCY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UOM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DISCOUNTTYPE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CANCELLED" NUMBER, 
	"DISCOUNTVALUE" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"OIC_FLOW_ID" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ID" NUMBER, 
	"FILE_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NUMBER" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

