
  CREATE TABLE "INTEGRATIONS"."LTF_SUPPLIER_PAYMENT_METHOD_DETAILS" 
   (	"VENDOR_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYEE_ID" NUMBER, 
	"VENDOR_SITE_ID" NUMBER, 
	"VENDOR_SITE_CODE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_SITE_ID" NUMBER, 
	"PAYMENT_METHOD_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

