
  CREATE TABLE "INTEGRATIONS"."LTF_PROD_SCHEDULES_TBL" 
   (	"UUID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION_UUID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTERNAL_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOM_REFERENCE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE_UUID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PLANNED_QUANTITY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PLANNED_START_TIME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"INSTANCE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RESOURCE_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("CUSTOM_REFERENCE", "INSTANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

