
  CREATE TABLE "INTEGRATIONS"."LTF_REDZONE_API_DETAILS" 
   (	"CLIENT_ID" VARCHAR2(500 BYTE), 
	"CLIENT_SECRET" VARCHAR2(500 BYTE), 
	"ACCESS_TOKEN" VARCHAR2(5000 BYTE), 
	"ACCESS_TOKEN_TYPE" VARCHAR2(50 BYTE), 
	"ACCESS_TOKEN_EXPIRATION_DATE" VARCHAR2(50 BYTE)
   );

