
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_850_CARRIER_INFO_STG" 
   (	"TRADING_PARTNER_ID" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PURCHASE_ORDER_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CARRIER_TRANS_METHOD_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CARRIER_ALPHA_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CARRIER_ROUTING" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ROUTING_SEQUENCE_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"SERVICE_LEVEL_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PROCESSED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"SEQUENCE_ID" NUMBER, 
	"TARGET_SYSTEM_DOCUMENT_TYPE" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"TARGET_SYSTEM_DOCUMENT_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"TARGET_SYSTEM_DOCUMENT_LINE_NUMBER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

