
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_850_LINES_INT" 
   (	"TRANSACTION_ID" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"SOURCE_TRANSACTION_LINE_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"SOURCE_SCHEDULE_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_CATEGORY_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PRODUCT_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ORDERED_QUANTITY" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ORDERED_UOM_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_PO_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_PO_LINE_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ORIGINAL_CASES" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ORIGINAL_POUNDS" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"EDI_PRICE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ALLOW_CHRG_AMT" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ALLOW_CHRG_PERCENT" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE1" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE2" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER1" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CHAR1" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CHAR3" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CHAR2" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_NUMBER2" VARCHAR2(200 CHAR) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CHAR4" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PROCESSED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(8000 CHAR) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"SEQUENCE_ID" NUMBER, 
	"TARGET_SYSTEM_DOCUMENT_TYPE" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"TARGET_SYSTEM_DOCUMENT_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"TARGET_SYSTEM_DOCUMENT_LINE_NUMBER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

