
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_850_LINE_ITEMS_STG" 
   (	"TRADING_PARTNER_ID" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PURCHASE_ORDER_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"LINE_SEQUENCE_NUMBER" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PRODUCT_CHARACTERISTIC_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"AGENCY_QUALIFIER_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PRODUCT_DESCRIPTION_CODE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PRODUCT_DESCRIPTION" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"YES_OR_NO_RESPONSE" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"DATE_TIME_PERIOD" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP", 
	"PROCESSED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"SEQUENCE_ID" NUMBER, 
	"TARGET_SYSTEM_DOCUMENT_TYPE" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"TARGET_SYSTEM_DOCUMENT_NUMBER" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"TARGET_SYSTEM_DOCUMENT_LINE_NUMBER" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

