
  CREATE TABLE "INTEGRATIONS"."OIC_OUTBOUND_RUNS" 
   (	"OUTBOUND_RUN_ID" NUMBER NOT NULL ENABLE, 
	"OUTBOUND_LOOKUP_CODE" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"OVERALL_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"OVERALL_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"STARTER_INT_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"STARTER_INT_INSTANCE_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INITIATOR_INT_IDENTIFIER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"INITIATOR_INT_INSTANCE_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTRACTOR_INT_IDENTIFIER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTRACTOR_INT_INSTANCE_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTRACTOR_INT_INSTANCE_START" TIMESTAMP (6), 
	"EXTRACTOR_INT_INSTANCE_END" TIMESTAMP (6), 
	"EXTRACTOR_INT_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"POST_EXTRACT_INT_IDENTIFIER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"POST_EXTRACT_INT_INSTANCE_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"POST_EXTRACT_INT_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVER_INT_IDENTIFIER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVER_INT_INSTANCE_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVER_INT_INSTANCE_START" TIMESTAMP (6), 
	"DELIVER_INT_INSTANCE_END" TIMESTAMP (6), 
	"DELIVER_INT_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"OUTBOUND_STATUS_INT_IDENTIFIER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"OUTBOUND_STATUS_INT_INSTANCE_ID" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"OUTBOUND_STATUS_INT_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ARCHIVE_FILENAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DELIVER_TO_EMAIL" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ADDITIONAL_INFORMATION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."OIC_OUTBOUND_RUNS_PK" ON "INTEGRATIONS"."OIC_OUTBOUND_RUNS" ("OUTBOUND_RUN_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."OUTBOUND_RUN_ID_U" ON "INTEGRATIONS"."OIC_OUTBOUND_RUNS" ("OUTBOUND_RUN_ID", "OUTBOUND_LOOKUP_CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."OIC_OUTBOUND_RUNS" ADD CONSTRAINT "OIC_OUTBOUND_RUNS_PK" PRIMARY KEY ("OUTBOUND_RUN_ID")
  USING INDEX "INTEGRATIONS"."OIC_OUTBOUND_RUNS_PK"  ENABLE;
ALTER TABLE "INTEGRATIONS"."OIC_OUTBOUND_RUNS" ADD CONSTRAINT "OUTBOUND_RUN_ID_U" UNIQUE ("OUTBOUND_RUN_ID", "OUTBOUND_LOOKUP_CODE")
  USING INDEX "INTEGRATIONS"."OUTBOUND_RUN_ID_U"  ENABLE;

