
  CREATE TABLE "INTEGRATIONS"."OIC_AUDIT_HIST" 
   (	"INSTANCE_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TRACKING_VAR_1_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRACKING_VAR_1_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRACKING_VAR_2_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRACKING_VAR_2_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRACKING_VAR_3_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRACKING_VAR_3_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"GENERAL_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SPECIFIC_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_1_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_1_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_2_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_2_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_3_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_3_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_4_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_4_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_5_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_5_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "INTEGRATIONS"."UPDATE_PARENT_STATUS" 
FOR UPDATE ON OIC_AUDIT_HIST
COMPOUND TRIGGER
    TYPE audit_record_type IS RECORD (
        parent_id   VARCHAR2(100 BYTE),
        general_status VARCHAR2(100 BYTE)
    );

    TYPE audit_table_type IS TABLE OF audit_record_type INDEX BY PLS_INTEGER;

    -- Declare a collection to store records
    audit_records audit_table_type;

BEFORE STATEMENT IS
BEGIN
    -- Initialize the collection before each statement
    audit_records := audit_table_type();
END BEFORE STATEMENT;

AFTER EACH ROW IS
BEGIN
    -- Store relevant data in the collection
    IF :NEW.PARENT_ID IS NOT NULL AND :NEW.GENERAL_STATUS IS NOT NULL AND :OLD.GENERAL_STATUS <> :NEW.GENERAL_STATUS THEN
        audit_records(audit_records.COUNT + 1).parent_id := :NEW.PARENT_ID;
        audit_records(audit_records.COUNT).general_status := :NEW.GENERAL_STATUS;
    END IF;
END AFTER EACH ROW;

AFTER STATEMENT IS
BEGIN
    -- Process the collection and update the parent rows
    FOR i IN 1..audit_records.COUNT LOOP
        UPDATE OIC_AUDIT_HIST
        SET GENERAL_STATUS = audit_records(i).general_status
        WHERE INSTANCE_ID = audit_records(i).parent_id;
    END LOOP;


END AFTER STATEMENT;

END update_parent_status;
/
ALTER TRIGGER "INTEGRATIONS"."UPDATE_PARENT_STATUS" ENABLE;

