
  CREATE TABLE "INTEGRATIONS"."OIC_INTEGRATION_RUNS" 
   (	"GROUP_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_REFERENCE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"OVERALL_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"OVERALL_MESSAGE" VARCHAR2(32000 BYTE) COLLATE "USING_NLS_COMP", 
	"HEADER_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_RECORD_COUNT" NUMBER, 
	"SUCCESS_RECORD_COUNT" NUMBER, 
	"ERROR_RECORD_COUNT" NUMBER, 
	"STARTER_INT_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STARTER_INT_INSTANCE_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ARCHIVE_FILENAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"STAGE_FILENAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSFORMED_FILENAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESSED_FILE_NUMBER" NUMBER, 
	"TOTAL_FILES_TO_PROCESS" NUMBER, 
	"INITIATOR_INT_IDENTIFIER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"INITIATOR_INT_INSTANCE_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSFORM_INT_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSFORM_INT_IDENTIFIER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSFORM_INT_INSTANCE_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSFORM_INT_INSTANCE_START" TIMESTAMP (6), 
	"TRANSFORM_INT_INSTANCE_END" TIMESTAMP (6), 
	"IMPORT_INT_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_INT_IDENTIFIER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_INT_INSTANCE_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_INT_INSTANCE_START" TIMESTAMP (6), 
	"IMPORT_INT_INSTANCE_END" TIMESTAMP (6), 
	"LOAD_REQUEST_ID" NUMBER, 
	"CALLBACK_PAYLOAD" CLOB COLLATE "USING_NLS_COMP", 
	"CALLBACK_INT_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CALLBACK_INT_IDENTIFIER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CALLBACK_INT_INSTANCE_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CALLBACK_INT_INSTANCE_START" TIMESTAMP (6), 
	"CALLBACK_INT_INSTANCE_END" TIMESTAMP (6), 
	"LOG_MANUALLY_PROCESSED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"SECOND_GROUP_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"INTEGRATION_GROUP_ID" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("CALLBACK_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

