
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_947_L_test_INTF" 
   (	"LOT_INTF_REC_ID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_LOT_INTF_SEQ".nextval, 
	"REFERENCE_STG_REC_ID" NUMBER, 
	"LINE_ITEM_STG_REC_ID" NUMBER, 
	"HEADER_ORDER_STG_REC_ID" NUMBER, 
	"HEADER_ORDER_INTF_REC_ID" NUMBER, 
	"LOTNUMBER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"LOTEXPIRATIONDATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTIONQUANTITY" NUMBER, 
	"TRANSACTIONINTERFACEID" NUMBER, 
	"ORIGINATIONDATE" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"PROCESSED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ERROR_CODE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("LOT_INTF_REC_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

