
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_947_XML_DATA_STG" 
   (	"XML_CONTENT_REC_ID" NUMBER DEFAULT "INTEGRATIONS".XXEDI_947_HEADER_ORDER_SEQ.nextval, 
	"FILE_NAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"XML_DATA" CLOB COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"PROCESSED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"OIC_INSTANCE_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_SYSTEM" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"DOC_TYPE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("XML_CONTENT_REC_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("XML_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

