
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_947_SUMMARY_STG" 
   (	"SUMMARY_STG_REC_ID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_SUMMARY_SEQ".nextval, 
	"HEADER_ORDER_STG_REC_ID" NUMBER NOT NULL ENABLE, 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"PROCESSED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ERROR_CODE" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("SUMMARY_STG_REC_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

