
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_947_LINES_INTF" 
   (	"LINES_INTF_REC_ID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_LINES_INTF_SEQ".nextval NOT NULL ENABLE, 
	"HEADER_ORDER_STG_REC_ID" NUMBER, 
	"XML_CONTENT_REC_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_LOCATION_NUMBER" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_CODE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"SOUCRE_HEADER_ID" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"SOUCRE_LINE_ID" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_MODE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"TRX_QTY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"TRX_UOM" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"HDR_DATE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_INV_CODE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"TRX_TYPE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ACC_ALIAS_COMBN" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NUMBER" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATION_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"USECURRENTCOSTFLAG" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTERNAL_SYS_TX_REF" VARCHAR2(256 CHAR) COLLATE "USING_NLS_COMP", 
	"LOT_NUMBER" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LOT_QUANTITY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LOT_SUB_INVENTORY_CODE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LOT_EXP_DATE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"PROCESSED_FLAG" VARCHAR2(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ERROR_CODE" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP", 
	"HEADER_ORDER_INTF_REC_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

