
  CREATE TABLE "INTEGRATIONS"."XXEDI_SCM_INB_947_INV_TRANSA_TEST_INTF" 
   (	"HEADER_ORDER_INTF_REC_ID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_HDR_ORD_STG_SEQ".nextval, 
	"HEADER_ORDER_STG_REC_ID" NUMBER, 
	"XML_CONTENT_REC_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTIONINTERFACEID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_TRX_INTF_SEQ".nextval, 
	"TRANSACTIONHEADERID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_TRX_HDR_SEQ".nextval, 
	"SOURCECODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'EDI', 
	"SOURCEHEADERID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_SOURCE_HDR_ID_SEQ".nextval, 
	"SOURCELINEID" NUMBER DEFAULT "INTEGRATIONS"."XXEDI_947_SOURCE_LINE_ID_SEQ".nextval, 
	"TRANSACTIONMODE" NUMBER DEFAULT 1, 
	"TRANSACTIONQUANTITY" NUMBER, 
	"TRANSACTIONUOM" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBINVENTORYCODE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'AVAILABLE', 
	"TRANSACTIONTYPENAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNTALIASCOMBINATION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEMNUMBER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATIONNAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"USECURRENTCOSTFLAG" BOOLEAN DEFAULT TRUE, 
	"LOTNUMBER" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"CREATED_BY_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
	"LAST_UPDATE_BY_ID" NUMBER, 
	"LAST_UPDATE_BY_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'OIC', 
	"PROCESSED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"ERROR_CODE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOTQTY" NUMBER, 
	"EXTERNALSYSTEMTRANSACTIONREFERENCE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTIONDATE" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LOTEXPIRATIONDATE" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"TRADING_PARTNER_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LINE_ITEM_STG_REC_ID" NUMBER, 
	 PRIMARY KEY ("TRANSACTIONINTERFACEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

