
  CREATE TABLE "INTEGRATIONS"."DOO_LINE_EXTRACT_PVO_INTF" 
   (	"ACTUAL_SHIP_DATE" TIMESTAMP (6), 
	"CANCELED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CANCELED_QTY" NUMBER, 
	"CATEGORY_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"COMP_SEQ_PATH" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"DELTA_TYPE" NUMBER, 
	"DISPLAY_LINE_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTENDED_AMOUNT" NUMBER, 
	"FULFILLED_QTY" NUMBER, 
	"FULFILLMENT_DATE" TIMESTAMP (6), 
	"HEADER_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"INVENTORY_ITEM_ID" NUMBER, 
	"INVENTORY_ORGANIZATION_ID" NUMBER, 
	"ITEM_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"LINE_NUMBER" NUMBER, 
	"LINE_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ON_HOLD" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"OPEN_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDERED_QTY" NUMBER, 
	"ORDERED_UOM" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"ORG_ID" NUMBER, 
	"ORIG_SYS_DOCUMENT_LINE_REF" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ORIG_SYS_DOCUMENT_REF" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"OWNER_ID" NUMBER, 
	"PARENT_LINE_ID" NUMBER, 
	"REFERENCE_LINE_ID" NUMBER, 
	"RMA_DELIVERED_QTY" NUMBER, 
	"ROOT_PARENT_LINE_ID" NUMBER, 
	"SCHEDULE_SHIP_DATE" TIMESTAMP (6), 
	"SHIPPED_QTY" NUMBER, 
	"SOURCE_LINE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_LINE_NUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ORDER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ORDER_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ORDER_SYSTEM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ORG_ID" NUMBER, 
	"SOURCE_SCHEDULE_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_SCHEDULE_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSFORM_FROM_LINE_ID" NUMBER, 
	"UNIT_LIST_PRICE" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."DOO_LINE_EXTRACT_PVO_INTF_PK" ON "INTEGRATIONS"."DOO_LINE_EXTRACT_PVO_INTF" ("LINE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."DOO_LINE_EXTRACT_PVO_INTF" ADD CONSTRAINT "DOO_LINE_EXTRACT_PVO_INTF_PK" PRIMARY KEY ("LINE_ID")
  USING INDEX "INTEGRATIONS"."DOO_LINE_EXTRACT_PVO_INTF_PK"  ENABLE;

