
  CREATE TABLE "INTEGRATIONS"."DOO_FULFILL_LINE_EXTRACT_PK_INTF" 
   (	"FULFILL_LINE_ID" NUMBER, 
	 CONSTRAINT "DOO_FULFILL_LINE_EXTRACT_PK" PRIMARY KEY ("FULFILL_LINE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

