
  CREATE TABLE "INTEGRATIONS"."DOO_HEADER_EFF_EXTRACT_PK_INTF" 
   (	"HEADERID" NUMBER, 
	 CONSTRAINT "DOO_HEADER_EFF_EXTRACT_PK" PRIMARY KEY ("HEADERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

