
  CREATE TABLE "INTEGRATIONS"."DOO_HEADER_EFF_EXTRACT_PVO_INTF" 
   (	"CATEGORY" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_CONTEXTCODE" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EFFLINEID" NUMBER, 
	"DOO_HEADERS_ADD_INFO_EDI_EDI850DEPARTMENT" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI850PRIMARYPOTYPECODE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI850REFERENCEID" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI850TSETPURPOSECODE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI855DATE" DATE, 
	"DOO_HEADERS_ADD_INFO_EDI_EDI855OVERRIDE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI855REVISEDORDER" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI856RESENDCHECKBOX" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI856RESENDDATE" DATE, 
	"DOO_HEADERS_ADD_INFO_EDI_EDI940RESENDCHECKBOX" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI940RESENDDATE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_EDI_EDI945SHIPPINGOVERRIDE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_SO__ADD__INFO_CONTEXTCODE" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_SO__ADD__INFO_EFFLINEID" NUMBER, 
	"DOO_HEADERS_ADD_INFO_SO__ADD__INFO_BROKER" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"DOO_HEADERS_ADD_INFO_SO__ADD__INFO_SALESPERSON" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"HEADERID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."DOO_HEADER_EFF_EXTRACT_PK_INTF" ON "INTEGRATIONS"."DOO_HEADER_EFF_EXTRACT_PVO_INTF" ("HEADERID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."DOO_HEADER_EFF_EXTRACT_PVO_INTF" ADD CONSTRAINT "DOO_HEADER_EFF_EXTRACT_PK_INTF" PRIMARY KEY ("HEADERID")
  USING INDEX "INTEGRATIONS"."DOO_HEADER_EFF_EXTRACT_PK_INTF"  ENABLE;

