
  CREATE TABLE "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_POINT_PVO_INTF" 
   (	"CONTACT_POINT_PURPOSE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_POINT_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_VALUE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_POINT_ID" NUMBER(18,0), 
	"CONTACT_POINT_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"RELATIONSHIP_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"RELATIONSHIP_TYPE_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"ROLE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_POINT_PVO_INTF_PK" ON "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_POINT_PVO_INTF" ("CONTACT_POINT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_POINT_PVO_INTF" ADD CONSTRAINT "HZ_ACCOUNT_CONTACT_POINT_PVO_INTF_PK" PRIMARY KEY ("CONTACT_POINT_ID")
  USING INDEX "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_POINT_PVO_INTF_PK"  ENABLE;

