
  CREATE TABLE "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_POINT_PK_INTF" 
   (	"CONTACT_POINT_ID" NUMBER, 
	 CONSTRAINT "HZ_ACCOUNT_CONTACT_POINT_PK" PRIMARY KEY ("CONTACT_POINT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

