
  CREATE TABLE "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_RELATIONSHIP_PVO_INTF" 
   (	"CONTACT_PERSON_PARTY_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"PERSON_FIRST_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_LAST_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_LAST_NAME_PREFIX" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_MIDDLE_NAME" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_NAME_SUFFIX" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_PRE_NAME_ADJUNCT" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_PREVIOUS_LAST_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PHONE_AREA_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PHONE_COUNTRY_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PHONE_EXTENSION" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PERSON_PARTY_PRIMARY_PHONE_NUMBER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CUST_ACCOUNT_ROLE_ID" NUMBER(18,0), 
	"ACCOUNT_CONTACT_CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_CREATED_BY_MODULE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_CREATION_DATE" TIMESTAMP (6), 
	"ACCOUNT_CONTACT_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"ACCOUNT_CONTACT_LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_ORIG_SYSTEM_REFERENCE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_PRIMARY_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_ROLE_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CONTACT_STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_CONTACT_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_DEPARTMENT_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_JOB_TITLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_JOB_TITLE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"PERSON_CREATED_BY_DISPLAY_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"RELATIONSHIP_LAST_UPDATE_DATE" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_RELATIONSHIP_PVO_INTF_PK" ON "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_RELATIONSHIP_PVO_INTF" ("CUST_ACCOUNT_ROLE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_RELATIONSHIP_PVO_INTF" ADD CONSTRAINT "HZ_ACCOUNT_CONTACT_RELATIONSHIP_PVO_INTF_PK" PRIMARY KEY ("CUST_ACCOUNT_ROLE_ID")
  USING INDEX "INTEGRATIONS"."HZ_ACCOUNT_CONTACT_RELATIONSHIP_PVO_INTF_PK"  ENABLE;

