
  CREATE TABLE "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_RELATIONSHIP_PVO_INTF" 
   (	"CUST_ACCT_RELATE_ID" NUMBER, 
	"ACCOUNT_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY_MODULE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"CUST_ACCOUNT_ID" NUMBER, 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"BILL_TO_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY_MODULE2" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_RECIPROCAL_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"END_DATE" DATE, 
	"SHIP_TO_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"PARTY_NAME" VARCHAR2(360 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_RELATIONSHIP_PVO_INTF_PK" ON "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_RELATIONSHIP_PVO_INTF" ("CUST_ACCT_RELATE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_RELATIONSHIP_PVO_INTF" ADD CONSTRAINT "HZ_CUSTOMER_ACCOUNT_RELATIONSHIP_PVO_INTF_PK" PRIMARY KEY ("CUST_ACCT_RELATE_ID")
  USING INDEX "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_RELATIONSHIP_PVO_INTF_PK"  ENABLE;

