
  CREATE TABLE "INTEGRATIONS"."HZ_CUST_ACCT_SITE_DFF_PK_INTF" 
   (	"CUSTACCTSITEID" NUMBER, 
	 CONSTRAINT "HZ_CUST_ACCT_SITE_DFF_PK" PRIMARY KEY ("CUSTACCTSITEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

