
  CREATE TABLE "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_PVO_INTF" 
   (	"ACCOUNT_ESTABLISHED_DATE" DATE, 
	"ACCOUNT_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_TERMINATION_DATE" DATE, 
	"ARRIVALSETS_INCLUDE_LINES_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTOPAY_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMENTS" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"COTERMINATE_DAY_MONTH" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY_MODULE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"CUST_ACCOUNT_ID" NUMBER, 
	"CUSTOMER_CLASS_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_TYPE_PREFERENCE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPOSIT_REFUND_METHOD" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"HELD_BILL_EXPIRATION_DATE" DATE, 
	"HOLD_BILL_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_BATCH_ID" NUMBER, 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"NPA_NUMBER" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"ORIG_SYSTEM_REFERENCE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_ID" NUMBER, 
	"SELLING_PARTY_ID" NUMBER, 
	"SOURCE_CODE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_UPDATE_DATE" DATE, 
	"TAX_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_HEADER_LEVEL_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_ROUNDING_RULE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_PVO_INTF_PK" ON "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_PVO_INTF" ("CUST_ACCOUNT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_PVO_INTF" ADD CONSTRAINT "HZ_CUSTOMER_ACCOUNT_PVO_INTF_PK" PRIMARY KEY ("CUST_ACCOUNT_ID")
  USING INDEX "INTEGRATIONS"."HZ_CUSTOMER_ACCOUNT_PVO_INTF_PK"  ENABLE;

