
  CREATE TABLE "INTEGRATIONS"."HZ_CUST_ACCOUNT_ROLES_DFF_PVO_INTF" 
   (	"CANAL_DE_DISTRIBUICAO" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATEDBY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATIONDATE" TIMESTAMP (6), 
	"FLEX_CONTEXT" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"FLEXFIELD_CODE" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTUPDATEDATE" TIMESTAMP (6), 
	"LASTUPDATEDBY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZACAO_DE_VENDA" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"SETOR_ATIVIDADE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"CUST_ACCOUNT_ROLE_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_CUST_ACCOUNT_ROLES_DFF_PVO_INTF_PK" ON "INTEGRATIONS"."HZ_CUST_ACCOUNT_ROLES_DFF_PVO_INTF" ("CUST_ACCOUNT_ROLE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_CUST_ACCOUNT_ROLES_DFF_PVO_INTF" ADD CONSTRAINT "HZ_CUST_ACCOUNT_ROLES_DFF_PVO_INTF_PK" PRIMARY KEY ("CUST_ACCOUNT_ROLE_ID")
  USING INDEX "INTEGRATIONS"."HZ_CUST_ACCOUNT_ROLES_DFF_PVO_INTF_PK"  ENABLE;

