
  CREATE TABLE "INTEGRATIONS"."HZ_CUST_ACCT_SITE_USE_LOC_PK_INTF" 
   (	"CUST_ACCOUNT_ID" NUMBER, 
	"SITE_USE_ID" NUMBER, 
	"PARTY_SITE_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "HZ_CUST_ACCT_SITE_USE_LOC_PK" PRIMARY KEY ("CUST_ACCOUNT_ID", "SITE_USE_ID", "PARTY_SITE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

