
  CREATE TABLE "INTEGRATIONS"."HZ_CUST_ACCT_DFF_PVO_INTF" 
   (	"LTF_BUYING_PARTY_ID_" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTUPDATEDATE" TIMESTAMP (6), 
	"CUST_ACCOUNT_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."CUST_ACCOUNT_ID" ON "INTEGRATIONS"."HZ_CUST_ACCT_DFF_PVO_INTF" ("CUST_ACCOUNT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_CUST_ACCT_DFF_PVO_INTF" ADD CONSTRAINT "CUST_ACCOUNT_ID" PRIMARY KEY ("CUST_ACCOUNT_ID")
  USING INDEX "INTEGRATIONS"."CUST_ACCOUNT_ID"  ENABLE;

