
  CREATE TABLE "INTEGRATIONS"."HZ_CUSTOMER_PK_INTF" 
   (	"PARTY_ID" NUMBER, 
	"PARTY_USAGE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "HZ_CUSTOMER_PK" PRIMARY KEY ("PARTY_ID", "PARTY_USAGE_CODE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

