
  CREATE TABLE "INTEGRATIONS"."HZ_PARTY_SITE_PK_INTF" 
   (	"PARTY_SITE_ID" NUMBER, 
	 CONSTRAINT "HZ_PARTY_SITE_PK" PRIMARY KEY ("PARTY_SITE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

