
  CREATE TABLE "INTEGRATIONS"."HZ_PARTY_USAGE_PVO_INTF" 
   (	"EFFECTIVE_START_DATE" DATE, 
	"PARTY_ASSIGNMENT_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"PARTY_ID" NUMBER(*,0), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"STATUS_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_NAME" VARCHAR2(360 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_USAGE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_USG_ASSIGNMENT_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_PARTY_USAGE_PVO_INTF_PK" ON "INTEGRATIONS"."HZ_PARTY_USAGE_PVO_INTF" ("PARTY_USG_ASSIGNMENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_PARTY_USAGE_PVO_INTF" ADD CONSTRAINT "HZ_PARTY_USAGE_PVO_INTF_PK" PRIMARY KEY ("PARTY_USG_ASSIGNMENT_ID")
  USING INDEX "INTEGRATIONS"."HZ_PARTY_USAGE_PVO_INTF_PK"  ENABLE;

