
  CREATE TABLE "INTEGRATIONS"."HZ_PARTY_SITE_PVO_INTF" 
   (	"END_DATE_ACTIVE" DATE, 
	"GLOBAL_LOCATION_NUMBER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"IDENTIFYING_ADDRESS_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LOCATION_ID" NUMBER, 
	"ORIG_SYSTEM_REFERENCE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_ID" NUMBER, 
	"PARTY_SITE_ID" NUMBER, 
	"PARTY_SITE_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTY_SITE_NUMBER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE_ACTIVE" DATE, 
	"STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."HZ_PARTY_SITE_PK_INTF" ON "INTEGRATIONS"."HZ_PARTY_SITE_PVO_INTF" ("PARTY_SITE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."HZ_PARTY_SITE_PVO_INTF" ADD CONSTRAINT "HZ_PARTY_SITE_PK_INTF" PRIMARY KEY ("PARTY_SITE_ID")
  USING INDEX "INTEGRATIONS"."HZ_PARTY_SITE_PK_INTF"  ENABLE;

