
  CREATE TABLE "INTEGRATIONS"."INV_TRANSFER_ORDER_HEADER_EXTRACT_PVO_INTF" 
   (	"BUDGET_CONTROL_ENABLED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"FULFILL_ORCHESTRATION_REQUIRED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"HEADER_ID" NUMBER, 
	"HEADER_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ORDERED_DATE" TIMESTAMP (6), 
	"REQ_BU_ID" NUMBER, 
	"SOURCE_TYPE_LOOKUP" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_TRANSFER_ORDER_HEADER_EXTRACT_PK_INTF" ON "INTEGRATIONS"."INV_TRANSFER_ORDER_HEADER_EXTRACT_PVO_INTF" ("HEADER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_TRANSFER_ORDER_HEADER_EXTRACT_PVO_INTF" ADD CONSTRAINT "INV_TRANSFER_ORDER_HEADER_EXTRACT_PK_INTF" PRIMARY KEY ("HEADER_ID")
  USING INDEX "INTEGRATIONS"."INV_TRANSFER_ORDER_HEADER_EXTRACT_PK_INTF"  ENABLE;

