
  CREATE TABLE "INTEGRATIONS"."INV_UOM_PK_INTF" 
   (	"UNIT_OF_MEASURE_ID" NUMBER, 
	"UOM_CLASS" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "INV_UOM_PK" PRIMARY KEY ("UNIT_OF_MEASURE_ID", "UOM_CLASS")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

