
  CREATE TABLE "INTEGRATIONS"."INV_LOT_NUMBERS_EXTRACT_PK_INTF" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"LOT_NUMBER" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATION_ID" NUMBER, 
	 CONSTRAINT "INV_LOT_NUMBERS_EXTRACT_PK" PRIMARY KEY ("INVENTORY_ITEM_ID", "ORGANIZATION_ID", "LOT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

