
  CREATE TABLE "INTEGRATIONS"."INV_ONHAND_EXTRACT_PK_INTF" 
   (	"INVENTORY_ITEM_ID" NUMBER(*,0), 
	"ONHAND_QUANTITIES_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_ONHAND_EXTRACT_PK_INTF_PK" ON "INTEGRATIONS"."INV_ONHAND_EXTRACT_PK_INTF" ("INVENTORY_ITEM_ID", "ONHAND_QUANTITIES_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_ONHAND_EXTRACT_PK_INTF" ADD CONSTRAINT "INV_ONHAND_EXTRACT_PK_INTF_PK" PRIMARY KEY ("INVENTORY_ITEM_ID", "ONHAND_QUANTITIES_ID")
  USING INDEX "INTEGRATIONS"."INV_ONHAND_EXTRACT_PK_INTF_PK"  ENABLE;

