
  CREATE TABLE "INTEGRATIONS"."INV_ITEM_RELATIONSHIP_PK_INTF" 
   (	"ITEM_RELATIONSHIP_ID" NUMBER, 
	 CONSTRAINT "INV_ITEM_RELATIONSHIP_PK" PRIMARY KEY ("ITEM_RELATIONSHIP_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

