
  CREATE TABLE "INTEGRATIONS"."INV_ONHAND_EXTRACT_PVO_INTF" 
   (	"AGING_EXPIRATION_DATE" TIMESTAMP (6), 
	"AGING_ONSET_DATE" TIMESTAMP (6), 
	"INVENTORY_ITEM_ID" NUMBER(*,0), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LOCATOR_ID" NUMBER(*,0), 
	"LOT_NUMBER" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATION_ID" NUMBER(*,0), 
	"OWNING_ENTITY_ID" NUMBER(*,0), 
	"OWNING_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_TRANSACTION_QUANTITY" NUMBER(*,0), 
	"SECONDARY_TRANSACTION_QUANTITY" NUMBER(*,0), 
	"SECONDARY_UOM_CODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"STANDARD_PACK_UOM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBINVENTORY_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_QUANTITY" NUMBER(*,0), 
	"TRANSACTION_UOM_CODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NUMBER" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"ITEM_PRIMARY_UOM_CODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"SHELF_LIFE_CODE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SHELF_LIFE_DAYS" NUMBER, 
	"ONHAND_QUANTITIES_ID" NUMBER(*,0), 
	"VENDOR_SITE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_ONHAND_EXTRACT_PVO_INTF_PK" ON "INTEGRATIONS"."INV_ONHAND_EXTRACT_PVO_INTF" ("ONHAND_QUANTITIES_ID", "INVENTORY_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_ONHAND_EXTRACT_PVO_INTF" ADD CONSTRAINT "INV_ONHAND_EXTRACT_PVO_INTF_PK" PRIMARY KEY ("ONHAND_QUANTITIES_ID", "INVENTORY_ITEM_ID")
  USING INDEX "INTEGRATIONS"."INV_ONHAND_EXTRACT_PVO_INTF_PK"  ENABLE;

