
  CREATE TABLE "INTEGRATIONS"."INV_ITEM_SUBINVENTORY_PVO_INTF" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"SECONDARY_INVENTORY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_SUBINVENTORY_FLAG" NUMBER, 
	"PICKING_ORDER" NUMBER, 
	"MINMAX_QUANTITY_UOM" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"MIN_MINMAX_QUANTITY" NUMBER, 
	"MAX_MINMAX_QUANTITY" NUMBER, 
	"INVENTORY_PLANNING_CODE" NUMBER(9,0), 
	"FIXED_LOT_MULTIPLE" NUMBER(9,0), 
	"MINIMUM_ORDER_QUANTITY" NUMBER, 
	"MAXIMUM_ORDER_QUANTITY" NUMBER, 
	"SOURCE_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ORGANIZATION_ID" NUMBER(18,0), 
	"SOURCE_SUBINVENTORY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE11" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE12" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE13" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE14" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE15" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUEST_ID" NUMBER(18,0), 
	"PREPROCESSING_LEAD_TIME" NUMBER, 
	"PROCESSING_LEAD_TIME" NUMBER, 
	"POSTPROCESSING_LEAD_TIME" NUMBER, 
	"JOB_DEFINITION_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_DEFINITION_PACKAGE" VARCHAR2(900 BYTE) COLLATE "USING_NLS_COMP", 
	"PAR_LEVEL" NUMBER, 
	"PAR_UOM_CODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"DEFAULT_COUNT_TYPE_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PAR_MAX_QTY" NUMBER, 
	"QTY_COUNT_TOLERANCE" NUMBER, 
	"COUNT_REQUIRED" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_ITEM_SUBINVENTORY_PVO_INTF_PK" ON "INTEGRATIONS"."INV_ITEM_SUBINVENTORY_PVO_INTF" ("INVENTORY_ITEM_ID", "ORGANIZATION_ID", "SECONDARY_INVENTORY") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_ITEM_SUBINVENTORY_PVO_INTF" ADD CONSTRAINT "INV_ITEM_SUBINVENTORY_PVO_INTF_PK" PRIMARY KEY ("INVENTORY_ITEM_ID", "ORGANIZATION_ID", "SECONDARY_INVENTORY")
  USING INDEX "INTEGRATIONS"."INV_ITEM_SUBINVENTORY_PVO_INTF_PK"  ENABLE;

