
  CREATE TABLE "INTEGRATIONS"."INV_ITEM_CATEGORY_PVO_INTF" 
   (	"CATALOG_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CATALOG_CONTENT_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_SET_ID" NUMBER, 
	"CONTROL_LEVEL" NUMBER, 
	"DEFAULT_CATEGORY_ID" NUMBER, 
	"END_DATE" DATE, 
	"HIERARCHY_ENABLED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"MULT_ITEM_CAT_ASSIGN_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SHARING_CONTENT_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_CATEGORY_SET_ID" NUMBER, 
	"START_DATE" DATE, 
	"STATUS_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"STRUCTURE_ID" NUMBER, 
	"VALIDATE_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_SET_NAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CATALOG_DESCRIPTION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"CATALOG_TRANSLATION_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CATEGORY_CODE" VARCHAR2(820 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_CONTENT_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"END_DATE_ACTIVE" DATE, 
	"CATEGORY_BASE_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"SEGMENT1" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT10" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT11" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT12" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT13" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT14" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT15" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT16" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT17" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT18" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT19" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT2" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT20" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT3" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT4" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT5" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT6" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT7" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT8" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SEGMENT9" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE_ACTIVE" DATE, 
	"CATEGORY_ID" NUMBER, 
	"CATEGORY_SET_ID2" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_DESCRIPTION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATION_LANGUAGE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSLATION_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"CATEGORY_CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY_CREATION_DATE" TIMESTAMP (6), 
	"CATEGORY_LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CATEGORY_LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATION_ID" NUMBER, 
	"VALID_CATEGORY_END_DATE" DATE, 
	"VALID_CATEGORY_LAST_UPDATE_DATE" TIMESTAMP (6)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_ITEM_CATEGORY_PVO_INTF_PK" ON "INTEGRATIONS"."INV_ITEM_CATEGORY_PVO_INTF" ("CATEGORY_SET_ID", "ORGANIZATION_ID", "CATEGORY_ID", "INVENTORY_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_ITEM_CATEGORY_PVO_INTF" ADD CONSTRAINT "INV_ITEM_CATEGORY_PVO_INTF_PK" PRIMARY KEY ("CATEGORY_SET_ID", "ORGANIZATION_ID", "CATEGORY_ID", "INVENTORY_ITEM_ID")
  USING INDEX "INTEGRATIONS"."INV_ITEM_CATEGORY_PVO_INTF_PK"  ENABLE;

