
  CREATE TABLE "INTEGRATIONS"."INV_ITEM_SUBINVENTORY_PK_INTF" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"SECONDARY_INVENTORY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "INV_ITEM_SUBINVENTORY_PK" PRIMARY KEY ("INVENTORY_ITEM_ID", "ORGANIZATION_ID", "SECONDARY_INVENTORY")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

