
  CREATE TABLE "INTEGRATIONS"."INV_TRANSFER_ORDER_HEADER_EXTRACT_PK_INTF" 
   (	"HEADER_ID" NUMBER, 
	 CONSTRAINT "INV_TRANSFER_ORDER_HEADER_EXTRACT_PK" PRIMARY KEY ("HEADER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

