
  CREATE TABLE "INTEGRATIONS"."INV_ITEM_PK_INTF" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"INVENTORY_ORGANIZATION_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	 CONSTRAINT "INV_ITEM_PK" PRIMARY KEY ("INVENTORY_ITEM_ID", "INVENTORY_ORGANIZATION_ID", "ORGANIZATION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

