
  CREATE TABLE "INTEGRATIONS"."INV_TRANDING_PARTNER_ITEMS_PVO_INTF" 
   (	"ATTRIBUTE1" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE11" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE12" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE13" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE14" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE15" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE16" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE17" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE18" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE19" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE20" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE21" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE22" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE23" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE24" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE25" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE26" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE27" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE28" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE29" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE30" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_NUMBER1" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER10" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER2" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER3" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER4" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER5" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER6" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER7" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER8" NUMBER(*,0), 
	"ATTRIBUTE_NUMBER9" NUMBER(*,0), 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
	"AVERAGE_RATING_NUMBER" NUMBER(*,0), 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_FROM_TPI_ID" NUMBER(*,0), 
	"CREATION_DATE" TIMESTAMP (6), 
	"END_DATE" DATE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"PART_STATUS_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"TP_ITEM_DESC" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"TP_ITEM_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TP_ITEM_NUMBER" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"TP_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"TRADING_PARTNER_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_TRANDING_PARTNER_ITEMS_PVO_INTF_PK" ON "INTEGRATIONS"."INV_TRANDING_PARTNER_ITEMS_PVO_INTF" ("TP_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_TRANDING_PARTNER_ITEMS_PVO_INTF" ADD CONSTRAINT "INV_TRANDING_PARTNER_ITEMS_PVO_INTF_PK" PRIMARY KEY ("TP_ITEM_ID")
  USING INDEX "INTEGRATIONS"."INV_TRANDING_PARTNER_ITEMS_PVO_INTF_PK"  ENABLE;

