
  CREATE TABLE "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PK_INTF" 
   (	"RESERVATION_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PK_INTF_PK" ON "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PK_INTF" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PK_INTF" ADD CONSTRAINT "INV_RESERVATIONS_EXTRACT_PK_INTF_PK" PRIMARY KEY ("RESERVATION_ID")
  USING INDEX "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PK_INTF_PK"  ENABLE;

