
  CREATE TABLE "INTEGRATIONS"."INV_ORG_PARAMETERS_PK_INTF" 
   (	"ORGANIZATION_ID" NUMBER, 
	 CONSTRAINT "INV_ORG_PARAMETERS_PK" PRIMARY KEY ("ORGANIZATION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

