
  CREATE TABLE "INTEGRATIONS"."INV_UOM_PVO_INTF" 
   (	"BASE_UOM_FLAG" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"DISABLE_DATE" DATE, 
	"JOB_DEFINITION_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_DEFINITION_PACKAGE" VARCHAR2(3600 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STANDARD_PACK_FLAG" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT_OF_MEASURE_ID" NUMBER, 
	"UOM_CLASS" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"UOM_CODE" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_UOM_PVO_INTF_PK" ON "INTEGRATIONS"."INV_UOM_PVO_INTF" ("UNIT_OF_MEASURE_ID", "UOM_CLASS") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_UOM_PVO_INTF" ADD CONSTRAINT "INV_UOM_PVO_INTF_PK" PRIMARY KEY ("UNIT_OF_MEASURE_ID", "UOM_CLASS")
  USING INDEX "INTEGRATIONS"."INV_UOM_PVO_INTF_PK"  ENABLE;

