
  CREATE TABLE "INTEGRATIONS"."INV_SUB_INVENTORY_EXTRACT_PVO_INTF" 
   (	"ASSET_INVENTORY" NUMBER, 
	"AVAILABILITY_TYPE" NUMBER, 
	"CARTONIZATION_FLAG" NUMBER, 
	"COUNT_METHOD" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"DEFAULT_COUNT_TYPE_CODE" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"DEFAULT_LOC_STATUS_ID" NUMBER, 
	"DEMAND_CLASS" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"DEPRECIABLE_FLAG" NUMBER, 
	"DESCRIPTION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DISABLE_DATE" DATE, 
	"DROPPING_ORDER" NUMBER, 
	"ENABLE_BULK_PICK" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"ENABLE_LOCATOR_ALIAS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"ENFORCE_ALIAS_UNIQUENESS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"INVENTORY_ATP_CODE" NUMBER, 
	"JOB_DEFINITION_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_DEFINITION_PACKAGE" VARCHAR2(3600 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION_ID" NUMBER, 
	"LOCATOR_TYPE" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"LPN_CONTROLLED_FLAG" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"PICKING_ORDER" NUMBER, 
	"PICK_METHODOLOGY" NUMBER, 
	"PICK_UOM_CODE" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"PLANNING_LEVEL" NUMBER, 
	"POSTPROCESSING_LEAD_TIME" NUMBER, 
	"PREPROCESSING_LEAD_TIME" NUMBER, 
	"PROCESSING_LEAD_TIME" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"QUANTITY_TRACKED" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"REQUISITION_APPROVAL_TYPE" NUMBER, 
	"RESERVABLE_TYPE" NUMBER, 
	"SECONDARY_INVENTORY_NAME" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_ORGANIZATION_ID" NUMBER, 
	"SOURCE_SUBINVENTORY" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_TYPE" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"STANDARD_PACK_TYPE" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_ID" NUMBER, 
	"STRUCTURE_INSTANCE_NUMBER" NUMBER, 
	"SUBINVENTORY_GROUP" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBINVENTORY_ID" NUMBER, 
	"SUBINVENTORY_TYPE" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBINVENTORY_USAGE" NUMBER, 
	"TASK_ID" NUMBER, 
	 CONSTRAINT "INV_SUB_INVENTORY_EXTRACT_PVO_INTF_PK" PRIMARY KEY ("SECONDARY_INVENTORY_NAME", "ORGANIZATION_ID", "SUBINVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

