
  CREATE TABLE "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PVO_INTF" 
   (	"CONTAINER_LPN_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"CROSSDOCK_CRITERIA_ID" NUMBER, 
	"CROSSDOCK_FLAG" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"DEMAND_SHIP_DATE" DATE, 
	"DEMAND_SOURCE_DELIVERY" NUMBER, 
	"DEMAND_SOURCE_HEADER_ID" NUMBER, 
	"DEMAND_SOURCE_LINE_DETAIL" NUMBER, 
	"DEMAND_SOURCE_LINE_ID" NUMBER, 
	"DEMAND_SOURCE_NAME" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"DEMAND_SOURCE_TYPE_ID" NUMBER, 
	"DETAILED_QUANTITY" NUMBER, 
	"EXCEPTION_CODE" VARCHAR2(600 BYTE) COLLATE "USING_NLS_COMP", 
	"INVENTORY_ITEM_ID" NUMBER, 
	"JOB_DEFINITION_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_DEFINITION_PACKAGE" VARCHAR2(3600 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATOR_ID" NUMBER, 
	"LOT_NUMBER" VARCHAR2(320 BYTE) COLLATE "USING_NLS_COMP", 
	"LPN_ID" NUMBER, 
	"N_COLUMN1" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"ORIG_DEMAND_SOURCE_HEADER_ID" NUMBER, 
	"ORIG_DEMAND_SOURCE_LINE_DETAIL" NUMBER, 
	"ORIG_DEMAND_SOURCE_LINE_ID" NUMBER, 
	"ORIG_DEMAND_SOURCE_LINE_NUMBER" VARCHAR2(600 BYTE) COLLATE "USING_NLS_COMP", 
	"ORIG_DEMAND_SOURCE_TYPE_ID" NUMBER, 
	"ORIG_SUPPLY_SOURCE_HEADER_ID" NUMBER, 
	"ORIG_SUPPLY_SOURCE_LINE_DETAIL" NUMBER, 
	"ORIG_SUPPLY_SOURCE_LINE_ID" NUMBER, 
	"ORIG_SUPPLY_SOURCE_TYPE_ID" NUMBER, 
	"PRIMARY_RESERVATION_QUANTITY" NUMBER, 
	"PRIMARY_UOM_CODE" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"PROJECT_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"REQUIREMENT_DATE" DATE, 
	"RESERVATION_ID" NUMBER, 
	"RESERVATION_QUANTITY" NUMBER, 
	"RESERVATION_UOM_CODE" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"REVISION" VARCHAR2(72 BYTE) COLLATE "USING_NLS_COMP", 
	"SALES_ORDER_LINE_NUMBER" VARCHAR2(600 BYTE) COLLATE "USING_NLS_COMP", 
	"SALES_ORDER_SHIPMENT_NUMBER" VARCHAR2(600 BYTE) COLLATE "USING_NLS_COMP", 
	"SECONDARY_DETAILED_QUANTITY" NUMBER, 
	"SECONDARY_RESERVATION_QUANTITY" NUMBER, 
	"SECONDARY_UOM_CODE" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"SERIAL_RESERVATION_QUANTITY" NUMBER, 
	"SHIP_READY_FLAG" NUMBER, 
	"SHIP_TO_PARTY_ID" NUMBER, 
	"SOURCE_FULFILLMENT_LINE_ID" NUMBER, 
	"SOURCE_LINE_NUMBER" VARCHAR2(600 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE_SHIPMENT_NUMBER" VARCHAR2(600 BYTE) COLLATE "USING_NLS_COMP", 
	"STAGED_FLAG" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBINVENTORY_CODE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLY_RECEIPT_DATE" DATE, 
	"SUPPLY_SOURCE_HEADER_ID" NUMBER, 
	"SUPPLY_SOURCE_LINE_DETAIL" NUMBER, 
	"SUPPLY_SOURCE_LINE_ID" NUMBER, 
	"SUPPLY_SOURCE_NAME" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLY_SOURCE_TYPE_ID" NUMBER, 
	"TASK_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PVO_INTF_PK" ON "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PVO_INTF" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PVO_INTF" ADD CONSTRAINT "INV_RESERVATIONS_EXTRACT_PVO_INTF_PK" PRIMARY KEY ("RESERVATION_ID")
  USING INDEX "INTEGRATIONS"."INV_RESERVATIONS_EXTRACT_PVO_INTF_PK"  ENABLE;

