
  CREATE TABLE "INTEGRATIONS"."LOOKUP_VALUES_PK_INTF" 
   (	"LANGUAGE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_TYPE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"SET_ID" NUMBER, 
	"SOURCE_LANG" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"VIEW_APPLICATION_ID" NUMBER, 
	 CONSTRAINT "LOOKUP_VALUES_PK" PRIMARY KEY ("LANGUAGE", "LOOKUP_CODE", "LOOKUP_TYPE", "SET_ID", "SOURCE_LANG", "VIEW_APPLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

