
  CREATE TABLE "INTEGRATIONS"."LOOKUP_VALUES_PVO_INTF" 
   (	"ATTRIBUTE1" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE11" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE12" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE13" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE14" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE15" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"DISPLAY_SEQUENCE" NUMBER(18,0), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"END_DATE_ACTIVE" TIMESTAMP (6), 
	"LANGUAGE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_CODE1" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_TYPE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_TYPE1" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"MEANING" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SET_ID" NUMBER(18,0), 
	"SET_ID1" NUMBER(18,0), 
	"SOURCE_LANG" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE_ACTIVE" TIMESTAMP (6), 
	"TAG" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"TERRITORY_CODE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"VIEW_APPLICATION_ID" NUMBER(18,0), 
	"VIEW_APPLICATION_ID1" NUMBER(18,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."LOOKUP_VALUES_PVO_INTF_PK" ON "INTEGRATIONS"."LOOKUP_VALUES_PVO_INTF" ("VIEW_APPLICATION_ID", "LOOKUP_TYPE", "LOOKUP_CODE", "SET_ID", "SOURCE_LANG", "LANGUAGE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."LOOKUP_VALUES_PVO_INTF" ADD CONSTRAINT "LOOKUP_VALUES_PVO_INTF_PK" PRIMARY KEY ("VIEW_APPLICATION_ID", "LOOKUP_TYPE", "LOOKUP_CODE", "SET_ID", "SOURCE_LANG", "LANGUAGE")
  USING INDEX "INTEGRATIONS"."LOOKUP_VALUES_PVO_INTF_PK"  ENABLE;

