
  CREATE TABLE "INTEGRATIONS"."LTF_BICC_CONTROL" 
   (	"DATA_STORE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_INCREMENTAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PK_TABLE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"INTERFACE_TABLE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_PREFIX" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"ENABLE_EXTRACT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_EXTRACT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTRACT_GROUP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

