
  CREATE TABLE "INTEGRATIONS"."WSH_DELIVERY_LINE_ASSIGNMENT_EXTRACT_PVO_INTF" 
   (	"CREATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6), 
	"DELIVERY_ASSIGNMENT_ID" NUMBER, 
	"DELIVERY_DETAIL_ID" NUMBER, 
	"DELIVERY_ID" NUMBER, 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE) COLLATE "USING_NLS_COMP", 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"REQUEST_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "INTEGRATIONS"."WSH_DELIVERY_LINE_ASSIGNMENT_EXTRACT_PK_INTF" ON "INTEGRATIONS"."WSH_DELIVERY_LINE_ASSIGNMENT_EXTRACT_PVO_INTF" ("DELIVERY_ASSIGNMENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "INTEGRATIONS"."WSH_DELIVERY_LINE_ASSIGNMENT_EXTRACT_PVO_INTF" ADD CONSTRAINT "WSH_DELIVERY_LINE_ASSIGNMENT_EXTRACT_PK_INTF" PRIMARY KEY ("DELIVERY_ASSIGNMENT_ID")
  USING INDEX "INTEGRATIONS"."WSH_DELIVERY_LINE_ASSIGNMENT_EXTRACT_PK_INTF"  ENABLE;

